#!/usr/bin/env python3
"""Freeze a pinned Cascadia evidence tree and scrub local telemetry. Never contacts a fleet."""
import argparse
import gzip
import hashlib
import ipaddress
import json
import math
import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
ENGINE_SOURCES = {
    'tools/inkling_moe_layer_ov.py',
    'crates/cascadia-engine-sparse-moe/src/inkling/gate.rs',
    'crates/cascadia-engine-sparse-moe/src/inkling/ov_moe.rs',
    'crates/cascadia-ov-genai-shim/cpp/shim.cpp',
}


def digest(data):
    return hashlib.sha256(data).hexdigest()


def scrub_text(text, hosts=()):
    for host in sorted(hosts, key=len, reverse=True):
        if host:
            text = text.replace(host, "REDACTED_HOST")
    def redact_ip(match):
        try:
            addr = ipaddress.ip_address(match.group())
        except ValueError:
            return match.group()
        return "REDACTED_IP" if (addr.is_private or addr in ipaddress.ip_network('100.64.0.0/10')) and not addr.is_loopback and not addr.is_unspecified else match.group()
    text = re.sub(r'(?<![\d.])(?:\d{1,3}\.){3}\d{1,3}(?![\d.])', redact_ip, text)
    text = re.sub(r'\benx[0-9a-fA-F]{12}\b', 'REDACTED_USB_INTERFACE', text)
    text = re.sub(r'\b(?:[0-9a-fA-F]{2}:){5}[0-9a-fA-F]{2}\b', 'REDACTED_MAC', text)
    text = re.sub(r'/(?:Users|home)/[A-Za-z0-9_.-]+', '/REDACTED_HOME', text)
    text = re.sub(r'\btate-\d+\b', 'REFERENCE_HOST', text)
    return text


def scrub(value, hosts=()):
    if isinstance(value, dict):
        return {k: scrub(v, hosts) for k, v in value.items()
                if k.lower() not in {'host', 'hostname', 'ip', 'mac', 'serial', 'serial_number'}}
    if isinstance(value, list):
        return [scrub(v, hosts) for v in value]
    if isinstance(value, str):
        return scrub_text(value, hosts)
    if isinstance(value, float) and not math.isfinite(value):
        return None
    return value


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--source', type=Path, required=True)
    ap.add_argument('--ref', required=True)
    ap.add_argument('--telemetry', type=Path, required=True)
    ap.add_argument('--output', type=Path, default=ROOT,
                    help='Artifact root; permits staging a new snapshot before replacing the checked-in evidence.')
    args = ap.parse_args()
    output = args.output
    def git(*argv):
        return subprocess.check_output(['git', '-C', str(args.source), *argv])
    commit = git('rev-parse', args.ref).decode().strip()
    paths = git('ls-tree', '-r', '--name-only', commit).decode().splitlines()
    telemetry_paths = sorted(args.telemetry.glob('*/telemetry.jsonl'))
    hosts = set()
    for path in telemetry_paths:
        for line in path.open():
            record = json.loads(line)
            if isinstance(record.get('host'), str):
                hosts.add(record['host'])
    entries = []
    def write(relative, original, cleaned, kind, source):
        dst = output / relative
        dst.parent.mkdir(parents=True, exist_ok=True)
        dst.write_bytes(cleaned)
        entries.append(dict(path=relative, source=source, kind=kind,
                            original_sha256=digest(original), sha256=digest(cleaned),
                            original_bytes=len(original), bytes=len(cleaned),
                            transformed=original != cleaned))
    for path in paths:
        p = Path(path)
        selected = (
            (path.startswith('autolab/') and p.suffix in {'.md', '.json', '.env', '.py', '.txt'})
            or (path.startswith('autolab/experiments/046_final_performance/') and p.suffix == '.csv')
            or (path.startswith('docs/perf/INKLING') and p.suffix == '.md')
            or path in {'docs/architectures/inkling.md', 'deploy/inkling-fleet/fleet.env'}
            or path in ENGINE_SOURCES
        )
        if not selected:
            continue
        original = git('show', f'{commit}:{path}')
        if p.suffix == '.json':
            cleaned = (json.dumps(scrub(json.loads(original), hosts), indent=2, allow_nan=False, ensure_ascii=False) + '\n').encode()
        else:
            cleaned = scrub_text(original.decode(), hosts).encode()
        write('reproduction/evidence/source/' + path, original, cleaned, 'git-blob', path)
    # Corpus 013 is locally generated by this study. External Dolly collection is excluded.
    corpus = 'autolab/experiments/013_acceptance_study/corpus.jsonl'
    if corpus in paths:
        original = git('show', f'{commit}:{corpus}')
        cleaned = ''.join(json.dumps(scrub(json.loads(line), hosts), ensure_ascii=False, allow_nan=False) + '\n'
                          for line in original.splitlines() if line.strip()).encode()
        write('reproduction/evidence/source/' + corpus, original, cleaned, 'git-blob', corpus)
    for path in telemetry_paths:
        original = path.read_bytes()
        cleaned = ''.join(json.dumps(scrub(json.loads(line), hosts), ensure_ascii=False, separators=(',', ':'), allow_nan=False) + '\n'
                          for line in original.splitlines() if line.strip()).encode()
        payload = gzip.compress(cleaned, compresslevel=9, mtime=0)
        write('reproduction/evidence/telemetry/' + path.parent.name + '.jsonl.gz', original, payload,
              'scrubbed-gzip-jsonl', 'operator-telemetry/' + path.parent.name + '/telemetry.jsonl')
    survey = 'autolab/experiments/046_final_performance/measurements.json'
    if survey in paths:
        phases = json.loads(git('show', f'{commit}:{survey}'))
        names = [p['phase'] + '.jsonl' for p in phases] + ['api-stats.jsonl']
        for name in names:
            path = args.telemetry / '046_final_performance' / name
            original = path.read_bytes()
            cleaned = ''.join(json.dumps(scrub(json.loads(line), hosts), ensure_ascii=False, separators=(',', ':'), allow_nan=False) + '\n'
                              for line in original.splitlines() if line.strip()).encode()
            write('reproduction/evidence/requests/046_final_performance/' + name + '.gz', original,
                  gzip.compress(cleaned, compresslevel=9, mtime=0), 'scrubbed-gzip-request-jsonl',
                  'operator-telemetry/046_final_performance/' + name)
    manifest = dict(source_repository='https://github.com/labscommunity/cascadia', source_commit=commit,
                    evidence_cutoff='2026-09-21',
                    transformations=['Drop host/IP/MAC/serial identity fields; replace private addresses and home paths.',
                                     'Replace observed telemetry host names and MAC-derived interface names.',
                                     'Normalize nonfinite JSON numbers to null; preserve scientific values otherwise.',
                                     'Compress telemetry deterministically; original hashes refer to uncompressed originals.'],
                    exclusions=['Model weights and binary residual captures (not present in this checkout).',
                                'External Dolly corpus, deployment logs, credentials and release-channel files.',
                                'Live fleet actions: no new inference, deployment or hardware changes.'], files=entries)
    dest = output / 'reproduction/evidence/manifest.json'
    dest.write_text(json.dumps(manifest, indent=2) + '\n')
    print(f'Imported {len(entries)} files at {commit}; {len(telemetry_paths)} telemetry archives; {sum(e["bytes"] for e in entries):,} bytes.')


if __name__ == '__main__':
    main()
